### PR TITLE
Update ofPath and ofPixel docs

### PR DESCRIPTION
**Pull request by javl**
ofPath:
* Fixes typo mentioned in #627 
* Changes `addVertex` into `moveTo` as `ofPath` does not have an `addVertex()` method.
* Updates descriptions to match their method's arguments.
* Changes variable name `line` in example code to `path` to better match `ofPath` object name.

ofPixel
* Fixes error mentioned in issue #606 (`setPixel` -> `setColor`)
* Clarifies the description of `getPixelIndex`

### CODE REVIEW

**Comment by arturoc** [comment]
Thanks, one thing. The inlined description is something autogenerated from the inlined comments in the code so that part shouldn't be modified. I'm going to merge it anyway since we are about to do a release and it'll just get overwritten by the new comments

**Comment by javl** [comment]
The inline was the same as the regular description so no problem.

**Comment by javl** [comment]
@arturoc Don't forget you can close issue #627 and #603

**Comment by javl** [comment]
I added a line for that purpose but guess I used the wrong wording or maybe the the keyword and issue number need to be together? I'll use the 'closes #' next time. Thanks.

**Pull request merged**
