### PR TITLE
Deprecate ofRect()

### PR DESCRIPTION
**Pull request by tpltnt**
`ofRect()` is deprecated (according to compiler warnings). These changes replace `ofRect()` with `ofDrawRectangle()` as suggested whereever appropriate in the function/method documentation and the tutorials.
Cheers
tpltnt

### CODE REVIEW

**Comment by kylemcdonald** [comment]
:+1: this is great!

**Comment by arturoc** [comment]
just realized that some of your PRs refer to changes in 0.9 so i'll wait till the release to merge them. thanks!

**Comment by tpltnt** [comment]
@arturoc can you add a label for 0.9 to find this PR more easily when time has come? I don't have the permission to do so.

**Comment by javl** [comment]
Wouldn't it be possible to make `ofDrawRect()` a typedef for `ofDrawRectangle()`? Looks slightly cleaner / shorter.

**Comment by tpltnt** [comment]
@javl short term yes, but we want people to use the new functionality in the long run. Also this is part of the official documentation where we should show people how to properly use oF.

**Comment by tpltnt** [comment]
@arturoc i synced with master. The PR can be merged again.

**Comment by arturoc** [comment]
thanks!

**Comment by arturoc** [comment]
@javi we discussed about using ofDrawRect but in the end decided that ofDrawRectangle is more concise also if you are using some kind of auto completion it shouldn't make much difference anyway

**Pull request merged**
