### PR TITLE
added korean ofSiteKR link

### PR DESCRIPTION
**Pull request by icq4ever**
added korean ofSite website link

### CODE REVIEW

**Comment by arturoc** [comment]
wow thanks!

**Comment by icq4ever** [comment]
super thanks for fast response!

**Comment by arturoc** [comment]
there's a problem with the link in the korean version to the english one, it seems to do nothing. btw, i see you've even translated several tutorials, thanks so much for doing this!

**Comment by icq4ever** [comment]
weired!! now it's working. can you check again?

**Pull request merged**
