### PR TITLE
adding small note about ofEasyCam (#618)

### PR DESCRIPTION
**Pull request by tpltnt**
Hi,

i added a small note to the ofEasyCam documentation to address issue [#618](https://github.com/openframeworks/openFrameworks/issues/618) in the openFrameworks repository.
Cheers,
tpltnt

### CODE REVIEW

**Comment by tpltnt** [comment]
@javl good catch! This typo is fixed now.

**Comment by tpltnt** [comment]
ping

**Comment by tpltnt** [comment]
ping

**Comment by arturoc** [comment]
this commit is not correct any more with the latest changes to the web but in any case it was adding a comment about a bug in ofEasyCam, what we should do is fix the bug not document it. i'm going to close it. thanks!

**Pull request closed without merging**
