### PR TITLE
Adding Archlinux getting Started

### PR DESCRIPTION
**Pull request by apparentVJ**

### CODE REVIEW

**Comment by arturoc** [comment]
thanks! can you include a link from the main raspbery pi setup guide to this one?

**Comment by apparentVJ** [comment]
I am not sure how to do that, not really familiar with git . :D

**Comment by arturoc** [comment]
ok, no worries, thanks!

**Comment by icq4ever** [comment]
superb! thanks!

**Comment by apparentVJ** [comment]
For nothing, thank **YOU** guys for this amazing toolkit !

---
Most of the things work, however, I am encountering some issues with (mesa, libEGL ... ) when compiling openCV, and of course the GLES example.
[error output - pastebin](http://pastebin.com/skDYEHnw)

Best,
Norbert

**Comment by icq4ever** [comment]
I added the link for archlinux from raspberry pi setup guide page.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
