### PR TITLE
Troubleshooting suggestion added

### PR DESCRIPTION
**Pull request by fcor**
This codec error is pretty common in people who are beginning in oF, hope this troubleshooting suggestion helps to avoid it.

### CODE REVIEW

**Comment by arturoc** [comment]
Thanks, can you specify that this is a windows only problem?

**Comment by fcor** [comment]
Hi Arturo, just added the clarification that this fix is for windows only. Thanks.

**Comment by arturoc** [comment]
thanks, can you add a link to the codecs? the link is in the setup guide already: https://openframeworks.cc/setup/vs/ but if someone finds it here better to have a clear link so they can find it easily: http://filehippo.com/download_klite_codec_pack/67445/

Also the text in the setup guide is more complete so if you can add that instead?

```
Starting in OF release 0.9.0 the video player now uses DirectShow and not QuickTime. To support QuickTime video files or files like MP4 video you will need to install the video codecs onto your machine. We recommend the K-Lite Codec Pack - Version 12.1.0 Full April 18th 2016 which is free to download and adds support for many video formats. Note: other newer versions of K-Lite might not contain the codecs needed for OF.
```

**Comment by fcor** [comment]
Great suggestion, this text add more context and why this is needed.

**Comment by edap** [comment]
@arturoc if it is ok for you I would merge this PR

**Pull request merged**
