### PR TITLE
reverted asciidoc plugin. 

### PR DESCRIPTION
**Pull request by icq4ever**

### CODE REVIEW

**Comment by arturoc** [comment]
just checked this and i don't get any unicode problems locally or in the server, which OS are you using?

**Comment by icq4ever** [comment]
still I have same problem. my OS is "ubuntu  14.04 LTS 64bit"

**Comment by icq4ever** [comment]
oh! there's a weird log. 
` ./auto_build.sh: 1: ./auto_build.sh: rouce: not found`

check below.
screenshot from 2016-01-28 12 37 21

**Comment by icq4ever** [comment]
hmm.. I think its really annoying you.

with modifying asciidoc plugin in my local server, everythings fine.
so if there is no issue with your repository.. then Ill PR without that file in the future. this is better for you and me.

:D

**Comment by arturoc** [comment]
:) no worries.

the script should say source not rouce, that's strange. can you try
running it manually:

```
source nikola/bin/activate
nikola build
```

if the first command doens't work it might be running under python 2.7
where that error was pretty common

i would also like to port the 2 tutorials that we have in asciidoc to
markdown since it's been very problematic, asciidoc is not very well
supported and has given me some headaches to to get it running properly.

**Comment by icq4ever** [comment]
> 
```
source nikola/bin/activate
nikola build
```

with this command, error is gone! hmm.. what's the problem?
but still warning with 'ja' remain..
anyway seems not big problem :)


---

>i would also like to port the 2 tutorials that we have in asciidoc to
markdown since it's been very problematic, asciidoc is not very well
supported and has given me some headaches to to get it running properly.

I agreed that. other translation team who working with asciidoc also struggling with this problem. a **much**. actually once I tried before already, but some of asciidoc formatting (like warning, tip) are unique. so I gave up:(

oneday the standard porting to markdown will finish, I'll happy to do that!

**Pull request merged**
