### PR TITLE
Update xcode.ko.md

### PR DESCRIPTION
**Pull request by alexhojinpark**
Updated the Korean version of Xcode Setup Guide.

### CODE REVIEW

**Comment by ofTheo** [comment]
Thanks!!

**Comment by icq4ever** [comment]
thanks!

**Comment by ofTheo** [comment]
hey @alexhojinpark - looks like the image paths might need adjusting: 
https://openframeworks.cc/ko/setup/xcode/ 

I think they need to link to here: 
https://openframeworks.cc/ko/setup/xcode/xcode_setup_assets/install-dialog.webp

instead of here: 
https://openframeworks.cc/setup/xcode/xcode_setup_assets/install-dialog.webp

**Comment by alexhojinpark** [comment]
Hi @ofTheo ! thanks for pointing that out! I'll make the adjustments accordingly.

**Pull request merged**
