### PR TITLE
Remove RPI for Arm7

### PR DESCRIPTION
**Pull request by jvcleave**
@arturoc , I let you decide if this is best to avoid confusion

### CODE REVIEW

**Comment by arturoc** [comment]
perhaps instead of removing it can you add (archlinux) after raspberry pi and link to https://github.com/openframeworks/ofSite/blob/master/content/setup/raspberrypi/Raspberry-Pi-Getting-Started-ArchLinux.md

**Comment by jvcleave** [comment]
@arturoc the `Raspberry-Pi-Getting-Started-ArchLinux` link isn't working - not sure why

**Comment by jvcleave** [comment]
I just changed it to `raspberry-pi-getting-started-archlinux` - I guess it's case-sensitive?

**Comment by arturoc** [comment]
yes, linux is always case sensitive and the web system removes all capitalization when generating the html

**Pull request merged**
