### PR TITLE
change "tutorials" section to LEARNING

### PR DESCRIPTION
**Pull request by sh0w**
here's what we're doing as part of the #ofDocSprint:

- rename "tutorials" to "learning"
- move the good existing tutorials to ofBook (thank you zach!)
- added how-to markdown templates
- only displaying categories whose folder names start with "howto_"
- "getting started" links (top left)
- link to external learning resources (top right)
- links to ofBook (bottom section)

note: we are keeping the old tutorials but only displaying how-tos!

### CODE REVIEW

**Comment by arturoc** [comment]
hey, we should ask the authors of the tutorials if they are ok with pulling them out. mostly the most recent ones. I know that some people have spent some time lately doing tutorials, modem zing old ones and translating to japanase and Korean.

I setup a docsprint branch so we could experiment there. Can we move this there until we get the ok from the original authors?

**Comment by ofZach** [comment]
I got permission from all of the authors we've moved over.  I think it's still possible to include links (by hand) to the translations of the chapters that used to be on the tutorials page.   

There are some tutorials that have been cut, happy to figure out a good home for them (or if they are too out of date, keeping them in a folder in the OF book for considering to be modernized)

**Comment by ofZach** [comment]
(also, I'm ok if we want to work on this on a branch, I think there was generally alot of excitement to see this content come online while we were here and it's great for the book to have it linked off the website.  I think there's a group of how-tos ready to come up shortly as well... )

**Comment by ofZach** [comment]
@sh0w can you swap out the link to the wiki to this url ? https://github.com/openframeworks/openFrameworks/wiki/Resources-for-Learning

**Pull request merged**
