### PR TITLE
Feature/no asciidoc

### PR DESCRIPTION
**Pull request by edap**
I've moved the old tutorials in asciidoc to markdown:
@arturoc , I've removed the codeblock part because out-of-date. The Qt creator part is missing. I've added some bulleptoints under the question "Why openFrameworks?", because they were missing, would be nice if you could double check them.
(Images have been scaled because they were huge)

### CODE REVIEW

**Comment by arturoc** [comment]
thanks so much! 

the problem with this is that it removes the korean translations, can you bring them back? i think it's better to let the original author convert them to markdown at some point than removing them.

also it's not merging with master right now but that's probably because of the recent commit that fixed a lot of links, if that's too problematic i can take a look

**Comment by edap** [comment]
it was not merging because of a merge conflict and the deleted files, can you chek now if everything is ok?

**Comment by arturoc** [comment]
almost :) but i think 000_introduction.asciidoc is still there? that one should go away, it's only the translations which should stay as they are

**Comment by arturoc** [comment]
thanks!

**Comment by icq4ever** [comment]
what a tough work! thanks a lot. I'll update korean documents as possible as I can.

**Comment by icq4ever** [comment]
markdown translated done!

**Pull request merged**
