### PR TITLE
Adjusted image path in xcode.ko.md

### PR DESCRIPTION
**Pull request by alexhojinpark**
Reference: [#815](https://github.com/openframeworks/ofSite/pull/815)

I attempted to locate a path for images from ko/setup/xcode/xcode_setup_assets/install-dialog.webp, but couldn't find a solution(Image does not show up on my preview). I tested with VS Code default preview, and it seems adding ./ might work.

So, changing this:
`install dialog for the command line tools`

to:
`install dialog for the command line tools`

Hope it works, Thank you.

### CODE REVIEW

**Comment by ofTheo** [comment]
I think this PR has a merge conflict @alexhojinpark  

But if this doesn't work we might need to use absolute urls like: 
 ```
![install dialog for the command line tools](https://openframeworks.cc/setup/xcode/xcode_setup_assets/install-dialog.webp)
```

**Comment by icq4ever** [comment]
@alexhojinpark it's not shown on offline preview in repo because markdown files will be generate to static html file so leave image url as original will be better I guess. hope this helps.

**Comment by alexhojinpark** [comment]
@ofTheo @icq4ever Thank you for the help. I've added absolute URLs. Should I create a new pull request for these changes? I'm not very familiar with the pull request process.

**Comment by icq4ever** [comment]
as I know as you update and pushed to your cloned repo(I mean github),
previous PR update automatically as well.

**Comment by alexhojinpark** [comment]
Thank you :)

**Comment by icq4ever** [comment]
@alexhojinpark still there are conflicts.

**Comment by alexhojinpark** [comment]
@icq4ever I'm assuming I have no permission to write or resolve conflicts, or I've done something wrong in Git commands while merging. I did a 'git pull' from master, switched to my branch, added, committed, and pushed to master.
Screenshot

**Comment by ofTheo** [comment]
Not sure what the issue was, but I fixed it! 
thanks @alexhojinpark

**Comment by alexhojinpark** [comment]
@ofTheo @icq4ever Thank you so much for the help :) have a great day!

**Pull request merged**
