### PR TITLE
Update to website sub nav links

### PR DESCRIPTION
**Pull request by mikechambers**
Updated the website sub-nav links. Removed IRC and link to mail-list (which was wrong). Changed order to emphasize forum and github. Added Slack  (to English version) as there has been some activity there lately.

### CODE REVIEW

**Comment by arturoc** [comment]
thanks, can you remove the capitalization as it's in the original?

**Comment by mikechambers** [comment]
Yeah. I just noticed all of the nav is lower case. Ill update.

**Comment by mikechambers** [comment]
Done. It is a little odd to have something like "Github" in lower case, but I understand the rest of the nav is lowercase.

At some point, it may be worth taking a close look at that.

**Comment by arturoc** [comment]
great, also can you leave forum in singular?

**Comment by mikechambers** [comment]
Done.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
