### PR TITLE
update korean pages

### PR DESCRIPTION
**Pull request by icq4ever**
korean page switch to online,
add some translated documents.
fix small layout for KR pages
update korean readme

### CODE REVIEW

**Comment by arturoc** [comment]
great! thanks!

**Comment by stroborobo** [comment]
Doesn't switching from openframeworks.kr to openframeworks.cc/ko break quite a lot of relative links? E.g. the tutorial link on the Korean index page.

**Comment by stroborobo** [comment]
Ah, that one's hard coded and not relative, I'll fix that as part of #427 later today.

**Comment by arturoc** [comment]
great thanks!

**Pull request merged**
