### PR TITLE
Added installation guide for CHIP

### PR DESCRIPTION
**Pull request by zealtv**

### CODE REVIEW

**Comment by edap** [comment]
Hey @zealtv does it work with 10.1 too?

**Comment by zealtv** [comment]
I haven't tested - CHIP was unfortunately quickly discontinued and the company went out of business.  May have a chance to test when home from holidays in a few weeks.

**Comment by edap** [comment]
Ok, so probably it does not make sense to put this instruction on the website, as all the platform in that page are supposed to be maintained.

**Comment by edap** [comment]
I would close this. @arturoc  ?

**Comment by arturoc** [comment]
thanks!

**Pull request closed without merging**
